### ISSUE TITLE
Default import?

### ISSUE THREAD

**Issue by benlieb** [rosskhanas/react-qr-code#251]
I have to do this for some reason:

```js
import { QRCode } from 'react-qr-code'; // note different from docs
```

**Comment by am-david-jiang** [comment]
Yes, I have the same problem. If I write `import QRCode from 'react-qr-code`, the website will not show up. Instead I get this error

![image](https://github.com/rosskhanas/react-qr-code/assets/6937496/afedda6a-f606-4201-8d10-be4be505ef73)
> Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> Check the render method of `QRCodeGenerator`.
>     at createFiberFromTypeAndProps (react-dom.development.js:28439:17)
>     at createFiberFromElement (react-dom.development.js:28465:15)
>     at reconcileSingleElement (react-dom.development.js:15750:23)
>     at reconcileChildFibers2 (react-dom.development.js:15808:35)
>     at reconcileChildren (react-dom.development.js:19167:28)
>     at updateHostComponent (react-dom.development.js:19924:3)
>     at beginWork (react-dom.development.js:21618:14)
>     at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
>     at invokeGuardedCallback (react-dom.development.js:4277:31)

It seems like the export is a object, like the  normal export in ES Module, not the default function component QRCode
(btw I use esbuild to bundle my code, the CLI command I use is `esbuild --bundle ./src/main.jsx --outfile=build/main.js --sourcemap --loader:.js=jsx --watch --servedir=build` for live reloading)

The problem is solved by wrapping QRCode with curly brackets. like `import { QRCode } from 'react-qr-code';`

**Comment by kblestarge** [comment]
I have to do the same. The named export is the only one that works for me too. TypeScript doesn't like it (unfortunately must use `@ts-ignore`) but it does work:
```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { QRCode } from 'react-qr-code';
```

**Comment by redneb** [comment]
I ran into this issue too.

Here's a very minimal example to reproduce this:
(Note: To make this example as minimal as possible, I am not using typescript and jsx syntax)

Create the following 2 files in a new directory:

`test.js`:
```
import {jsx as _jsx} from "react/jsx-runtime";
import * as ReactDOMServer from "react-dom/server";
import QRCode from "react-qr-code";

const qrcode = _jsx(QRCode, {value: "This is a test"});
console.log(ReactDOMServer.renderToStaticMarkup(qrcode));
```
`package.json`:
```
{
  "type": "module",
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-qr-code": "^2.0.15"
  }
}
```

The test script attempts to render `<QRCode value="this is a test" />` in server-side rendering mode, which should produce a string containing the corresponding HTML code.

If you try to run this with `node test.js` you will get an error. If you remove the line `"type": "module"` from `package.json`, then it runs fine. If you want to use `"type": "module"`, then you have to use `QRCode.default` instead of `QRCode`.

**Comment by redneb** [comment]
My workaround in typescript that allows me to use this package is:
```
import QRCode_import from "react-qr-code";
const QRCode = (QRCode_import as unknown as {default: typeof QRCode_import}).default;
```
This avoids the use of `@ts-ignore` and `QRCode` is actually typed.

**Comment by CanRau** [comment]
Facing the same.

Might be because `type` is not set to `module` https://nodejs.org/api/packages.html#type
and/or because `exports` is missing https://nodejs.org/api/packages.html#package-entry-points

**Comment by nklein** [comment]
Hmm... this is the only way that I found I am able to both successfully typecheck **and** reload a page with element on it without an error like: `Element type is invalid: expected a string refresh`.

In my file:
```
import { QRCode } from "react-qr-code";
```

And, then update `node_modules/react-qr-code/types/index.d.js` to add `export` in front of the `class QRCode` declaration.

**Comment by wirdehall** [comment]
Why haven't this been fixed yet? :O 
I used @redneb's hack to solve this, but it's weird that it's still here almost 1.5 years later.

**Comment by rosskhanas** [comment]
@wirdehall no idea why you don't have a default export. Here is in code: https://github.com/rosskhanas/react-qr-code/blob/b73da12efe7a09fe1bb64851ad519f0f85cee5b1/src/index.js#L52 It is also seem to be definde in ts: https://github.com/rosskhanas/react-qr-code/blob/b73da12efe7a09fe1bb64851ad519f0f85cee5b1/types/index.d.ts#L17

If you know what is wrong, just make a PR.

**Comment by wirdehall** [comment]
Can't see anything obviously wrong at a quick glance. Maybe it has something to do with how it's exported?

I'll clone the project tonight and take a closer look.

**Comment by wirdehall** [comment]
Yes it's confirmed, It's a problem with the build process/settings.
This lib currently only exports a CommonJS dist, most libraries today exports both CommonJS and ESM. (Or if it's a new lib, only ESM and drop backwards compatibility).

So any project currently trying to use this that have `"type": "module"` in their package.json will have this issue.

The solution is to upgrade the build step to export both module types.
To do this we need to migrate to Babel 7 as I don't think Babel 6 have support for ESM exports.

I'm contracting a cold here and feeling a bit under the weather so I don't have the energy to try the migration and create a PR for this today. Either someone else gives it a try or I might attack this when I'm feeling a bit better. :)

**Comment by rosskhanas** [comment]
Should be fixed in v2.1.1.
